customCommands:
  - key: "C"
    command: "git czg"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    output: terminal
gui:
  mouseEvents: false
  nerdFontsVersion: "3"
